### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DartPower** [dpteam/AwesomeDPT-WindowsOptima#1]
- [ ] Переписать код с оригинального репозитория.
- [ ] Внедрить свои фичи и адаптировать под себя снова.
- [ ] Перевести ReadMe на русский язык.
- [x] Сделать DPT лого в cmd файле.
- [ ] Исправить батник запуска

**Comment by DartPower** [comment]
* Сделать DPT лого в cmd файле.
